--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 1/10/2022 9:38:48 PM
-- Server version: 8.0.27
-- Client version: 4.1
--


SET NAMES 'utf8';

CREATE TABLE `dss.v1`.breathmachine (
  BreathMachineId char(36) NOT NULL DEFAULT '' COMMENT 'Khóa chính',
  BreathMachineCode varchar(20) NOT NULL DEFAULT '' COMMENT 'Mã máy thở',
  BreathMachineName varchar(255) NOT NULL DEFAULT '' COMMENT 'Tên máy thở',
  Amount int DEFAULT NULL COMMENT 'Số lượng máy thở',
  CreatedBy varchar(20) DEFAULT NULL COMMENT 'Người tạo',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  ModifiedBy varchar(20) DEFAULT NULL COMMENT 'Người chỉnh sửa',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày chỉnh sửa',
  PRIMARY KEY (BreathMachineId)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
COMMENT = 'Máy thở';

CREATE TABLE `dss.v1`.hospitalbed (
  HospitalBedId char(36) NOT NULL DEFAULT '' COMMENT 'Id giường bệnh',
  HospitalBedCode varchar(20) NOT NULL DEFAULT '' COMMENT 'Mã giường bệnh',
  Amount int DEFAULT NULL COMMENT 'Số lượng giường bệnh',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  CreatedBy varchar(20) DEFAULT NULL COMMENT 'Người tạo',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày sửa',
  ModifiedBy varchar(20) DEFAULT NULL COMMENT 'Người chỉnh sửa',
  PRIMARY KEY (HospitalBedId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
COMMENT = 'Giường bệnh';

CREATE TABLE `dss.v1`.province (
  ProvinceId char(36) NOT NULL DEFAULT '' COMMENT 'Khóa chính',
  ProvinceCode varchar(20) NOT NULL DEFAULT '' COMMENT 'Mã tỉnh',
  ProvinceName varchar(255) NOT NULL DEFAULT '' COMMENT 'Tên tỉnh',
  NumberCase int DEFAULT NULL COMMENT 'Số ca bệnh',
  PopulationDensity int DEFAULT NULL COMMENT 'Mật độ dân số',
  HospitalBed int DEFAULT NULL COMMENT 'Số lượng giường bệnh hiện có',
  BreathMachine int DEFAULT NULL COMMENT 'Số lượng máy thở hiện có',
  TestKit int DEFAULT NULL COMMENT 'Số lượng kit thử hiện có',
  NumberDeath int DEFAULT NULL COMMENT 'Số lượng người chết',
  NumberDoctorDispatch int DEFAULT NULL COMMENT 'Số lượng bác sỹ có thể lưu động',
  NumberHospital int DEFAULT NULL COMMENT 'Số lượng bệnh viện đa khoa',
  OneShotInjectionRate double DEFAULT NULL COMMENT 'Tỷ lệ tiêm mũi một',
  TwoShotInjectionRate double DEFAULT NULL COMMENT 'Tỷ lệ tiêm mũi 2',
  IndustrialArea int DEFAULT NULL COMMENT 'Số lượng khu công nghiệp',
  EpidemicLevel int DEFAULT NULL COMMENT 'Mức độ dịch bệnh: 1 - cấp 1, 2- cấp 2, 3-cấp 3, 4- cấp 4',
  CreateBy varchar(20) DEFAULT NULL COMMENT 'Người tạo',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  ModifiedBy varchar(20) DEFAULT NULL COMMENT 'Người chỉnh sửa',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày chỉnh sửa',
  PRIMARY KEY (ProvinceId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 260,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
COMMENT = 'Tỉnh thành';

CREATE TABLE `dss.v1`.testkit (
  TestKitId char(36) NOT NULL DEFAULT '' COMMENT 'Khóa chính',
  TestKitCode varchar(20) NOT NULL DEFAULT '' COMMENT 'Mã kit thử',
  TestKitName varchar(255) NOT NULL DEFAULT '' COMMENT 'Tên kít thử',
  Amount int DEFAULT NULL COMMENT 'Số lượng',
  CreatedBy varchar(20) DEFAULT NULL COMMENT 'Người tạo',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  ModifiedBy varchar(20) DEFAULT NULL COMMENT 'Người chỉnh sửa',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày chỉnh sửa',
  PRIMARY KEY (TestKitId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1092,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
COMMENT = 'Kít thử';

CREATE TABLE `dss.v1`.vaccine (
  VaccineId char(36) NOT NULL DEFAULT '' COMMENT 'Id',
  VaccineCode varchar(20) NOT NULL DEFAULT '' COMMENT 'Mã vaccine',
  VaccineName varchar(255) NOT NULL DEFAULT '' COMMENT 'Tên vaccine',
  Amount int DEFAULT NULL COMMENT 'Số lượng vaccine',
  CreatedBy varchar(20) DEFAULT NULL COMMENT 'Người tạo',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  ModifiedBy varchar(20) DEFAULT NULL COMMENT 'Người chỉnh sửa',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày chỉnh sửa',
  PRIMARY KEY (VaccineId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
COMMENT = 'Vắc xin';

INSERT INTO `dss.v1`.breathmachine(BreathMachineId, BreathMachineCode, BreathMachineName, Amount, CreatedBy, CreatedDate, ModifiedBy, ModifiedDate) VALUES
('bfe49c55-3487-11ec-9103-34e6d760b36f', 'BM001', 'Máy thở oxi loại 0', 2500, 'Group2', '2021-10-24 00:00:00', NULL, '2021-12-26 17:27:36'),
('dae82e58-6635-11ec-8f19-00155dbcd62f', 'BM002', 'Máy thở oxi loại 1', 3000, NULL, '2021-12-26 17:23:23', NULL, '2021-12-26 17:23:23');


INSERT INTO `dss.v1`.hospitalbed(HospitalBedId, HospitalBedCode, Amount, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) VALUES
('41c8c6e8-3487-11ec-9103-34e6d760b36f', 'HP001', 10000000, NULL, NULL, '2021-12-26 17:12:31', NULL);


INSERT INTO `dss.v1`.province(ProvinceId, ProvinceCode, ProvinceName, NumberCase, PopulationDensity, HospitalBed, BreathMachine, TestKit, NumberDeath, NumberDoctorDispatch, NumberHospital, OneShotInjectionRate, TwoShotInjectionRate, IndustrialArea, EpidemicLevel, CreateBy, CreatedDate, ModifiedBy, ModifiedDate) VALUES
('b6fae444-3497-11ec-9103-34e6d760b36f', 'P001', 'An Giang', 2206, 540, 3000, 500, 300000, 97, 300, 22, 24.46, 9.93, 7, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70b119a-3497-11ec-9103-34e6d760b36f', 'P002', 'Bà Rịa - Vũng Tàu', 240, 580, 1790, 200, 184000, 47, 280, 11, 84.66, 13.95, 11, 1, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70b1e2b-3497-11ec-9103-34e6d760b36f', 'P003', 'Bạc Liêu', 337, 340, 1850, 250, 189000, 4, 220, 9, 25.47, 7.34, 5, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70b228e-3497-11ec-9103-34e6d760b36f', 'P004', 'Bắc Giang', 16, 468, 2500, 200, 150000, 13, 280, 17, 45.7, 17.06, 5, 1, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70b267a-3497-11ec-9103-34e6d760b36f', 'P005', 'Bắc Kạn', 0, 65, 1000, 100, 90000, 0, 180, 10, 44.57, 9.04, 1, 1, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70b2a0c-3497-11ec-9103-34e6d760b36f', 'P006', 'Bắc Ninh', 37, 1664, 2100, 240, 95000, 16, 210, 15, 71.23, 28.98, 15, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70b2d90-3497-11ec-9103-34e6d760b36f', 'P007', 'Bến Tre', 173, 538, 5035, 310, 195000, 52, 210, 13, 43.5, 6.31, 2, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70b300d-3497-11ec-9103-34e6d760b36f', 'P008', 'Bình Dương', 4377, 900, 21000, 700, 490000, 3082, 180, 14, 124.59, 54.88, 28, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70b3285-3497-11ec-9103-34e6d760b36f', 'P009', 'Bình Định', 205, 245, 500, 50, 50000, 17, 360, 21, 44.86, 6.53, 7, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70b3945-3497-11ec-9103-34e6d760b36f', 'P010', 'Bình Phước', 175, 145, 590, 100, 70000, 13, 190, 13, 37.43, 10.08, 7, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70b6b83-3497-11ec-9103-34e6d760b36f', 'P011', 'Bình Thuận', 911, 158, 13600, 230, 95500, 60, 210, 14, 35.49, 7.97, 6, 1, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70b8a48-3497-11ec-9103-34e6d760b36f', 'P012', 'Cà Mau', 593, 226, 11000, 240, 105500, 10, 220, 15, 21.02, 7.75, 4, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70b923c-3497-11ec-9103-34e6d760b36f', 'P013', 'Cao Bằng', 0, 79, 1000, 120, 75500, 0, 80, 17, 38.2, 15.49, 1, 1, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70b980f-3497-11ec-9103-34e6d760b36f', 'P014', 'Cần Thơ', 670, 858, 5000, 270, 175500, 106, 260, 16, 38.67, 9.88, 10, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70b9e1c-3497-11ec-9103-34e6d760b36f', 'P015', 'Đà Nẵng', 450, 883, 1700, 210, 155500, 72, 260, 19, 99.28, 14.65, 6, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70ba4c7-3497-11ec-9103-34e6d760b36f', 'P016', 'Đắk Lắk', 788, 143, 1000, 210, 155500, 17, 260, 22, 14.95, 7.6, 1, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70ba9e8-3497-11ec-9103-34e6d760b36f', 'P017', 'Đắk Nông', 864, 100, 1000, 200, 150500, 6, 140, 19, 61.34, 0, 1, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70bad48-3497-11ec-9103-34e6d760b36f', 'P018', 'Điện Biên', 67, 65, 500, 70, 15500, 0, 40, 12, 105.73, 7.24, 0, 1, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70bb002-3497-11ec-9103-34e6d760b36f', 'P019', 'Đồng Nai', 58656, 547, 3500, 410, 270000, 503, 280, 21, 147.15, 49.44, 31, 1, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70bb809-3497-11ec-9103-34e6d760b36f', 'P020', 'Đồng Tháp', 9128, 468, 3500, 220, 210000, 220, 210, 19, 68.07, 0, 2, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70bbc4e-3497-11ec-9103-34e6d760b36f', 'P021', 'Gia Lai', 961, 101, 3700, 260, 215000, 5, 270, 15, 31.29, 0, 1, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70bbec5-3497-11ec-9103-34e6d760b36f', 'P022', 'Hà Giang', 237, 111, 1100, 170, 151000, 0, 70, 10, 63.71, 0, 1, 1, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70bc192-3497-11ec-9103-34e6d760b36f', 'P023', 'Hà Nam', 826, 991, 1100, 170, 151000, 0, 80, 14, 85.36, 0, 1, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70bc5f7-3497-11ec-9103-34e6d760b36f', 'P024', 'Hà Nội', 4595, 2398, 30000, 500, 451000, 37, 480, 50, 160.59, 61.44, 19, 3, 'Group2', '2021-10-24 00:00:00', NULL, '2021-12-26 17:11:03'),
('b70bc9a5-3497-11ec-9103-34e6d760b36f', 'P025', 'Hà Tĩnh', 515, 217, 1100, 180, 101000, 5, 210, 15, 58.5, 0, 19, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70bcc89-3497-11ec-9103-34e6d760b36f', 'P026', 'Hải Dương', 976, 1135, 2000, 280, 121000, 1, 210, 18, 63.81, 0, 11, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70bcf2c-3497-11ec-9103-34e6d760b36f', 'P027', 'Hải Phòng', 66, 1176, 2000, 280, 128000, 0, 290, 23, 69.31, 0, 8, 1, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70bd1bf-3497-11ec-9103-34e6d760b36f', 'P028', 'Hòa Bình', 44, 189, 1250, 100, 80000, 0, 290, 11, 77.1, 0, 2, 1, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70bd9dd-3497-11ec-9103-34e6d760b36f', 'P029', 'TP Hồ Chí Minh', 414827, 4363, 12500, 5000, 1350000, 16240, 0, 50, 181.3, 81.49, 22, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70bdd9c-3497-11ec-9103-34e6d760b36f', 'P030', 'Hậu Giang', 967, 449, 1200, 200, 100000, 3, 150, 16, 74.42, 0, 3, 1, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70be005-3497-11ec-9103-34e6d760b36f', 'P031', 'Hưng Yên', 368, 1347, 1200, 190, 102000, 1, 140, 18, 57.93, 0, 5, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70be243-3497-11ec-9103-34e6d760b36f', 'P032', 'Khánh Hòa', 8606, 242, 2200, 500, 122000, 89, 140, 19, 143.18, 43.36, 5, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70be493-3497-11ec-9103-34e6d760b36f', 'P033', 'Kiên Giang', 7102, 282, 2200, 480, 124000, 79, 270, 22, 68.87, 0, 6, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70be72f-3497-11ec-9103-34e6d760b36f', 'P034', 'Kon Tum', 120, 55, 1200, 80, 10000, 0, 20, 14, 45.86, 0, 1, 1, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70be9d2-3497-11ec-9103-34e6d760b36f', 'P035', 'Lai Châu', 8, 51, 1000, 40, 10000, 0, 20, 13, 86.27, 0, 1, 1, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70bf095-3497-11ec-9103-34e6d760b36f', 'P036', 'Lào Cai', 117, 115, 1000, 40, 10000, 0, 20, 17, 96.73, 0, 1, 1, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70bf9d3-3497-11ec-9103-34e6d760b36f', 'P037', 'Lạng Sơn', 219, 94, 1000, 40, 10000, 1, 20, 16, 111.36, 15.45, 2, 1, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70bfd1b-3497-11ec-9103-34e6d760b36f', 'P038', 'Lâm Đồng', 413, 145, 1500, 180, 90000, 1, 50, 15, 92.71, 0, 2, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70bff6d-3497-11ec-9103-34e6d760b36f', 'P039', 'Long An', 33710, 375, 5500, 280, 120000, 457, 80, 20, 201.45, 100, 36, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70c024a-3497-11ec-9103-34e6d760b36f', 'P040', 'Nam Định', 103, 1067, 2100, 260, 114000, 0, 140, 17, 31.45, 0, 2, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70c04bd-3497-11ec-9103-34e6d760b36f', 'P041', 'Nghệ An', 2019, 207, 4100, 480, 234000, 19, 170, 28, 37.3, 0, 6, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70c070d-3497-11ec-9103-34e6d760b36f', 'P042', 'Ninh Bình', 179, 60, 1200, 190, 14000, 0, 370, 18, 30.13, 0, 4, 2, 'Group2', '2021-10-24 00:00:00', NULL, '2021-12-26 21:48:31'),
('b70c0961-3497-11ec-9103-34e6d760b36f', 'P043', 'Ninh Thuận', 1150, 177, 1400, 190, 18000, 24, 200, 17, 95.24, 0, 4, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70c0ba4-3497-11ec-9103-34e6d760b36f', 'P044', 'Phú Thọ', 86, 423, 1500, 190, 18000, 0, 200, 20, 52.69, 0, 7, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70c0dfc-3497-11ec-9103-34e6d760b36f', 'P045', 'Phú Yên', 3125, 174, 2100, 230, 19500, 39, 250, 15, 77.7, 0, 4, 1, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70c103f-3497-11ec-9103-34e6d760b36f', 'P046', 'Quảng Bình', 1769, 112, 2100, 230, 19500, 39, 250, 15, 45.19, 0, 4, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70c14dd-3497-11ec-9103-34e6d760b36f', 'P047', 'Quảng Nam', 977, 142, 2300, 245, 21500, 12, 250, 20, 54.07, 0, 9, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70c190e-3497-11ec-9103-34e6d760b36f', 'P048', 'Quảng Ngãi', 388, 240, 2100, 210, 16500, 8, 120, 18, 49.09, 0, 6, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70c1be0-3497-11ec-9103-34e6d760b36f', 'P049', 'Quảng Ninh', 130, 220, 1800, 200, 14500, 0, 240, 23, 170.28, 71.27, 4, 1, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70c1e8c-3497-11ec-9103-34e6d760b36f', 'P050', 'Quảng Trị', 396, 135, 1800, 200, 14500, 2, 240, 21, 85.08, 0, 1, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70c2176-3497-11ec-9103-34e6d760b36f', 'P051', 'Sóc Trăng', 3180, 357, 1800, 200, 14500, 28, 280, 21, 85.08, 0, 1, 1, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70c2443-3497-11ec-9103-34e6d760b36f', 'P052', 'Sơn La', 276, 91, 1400, 150, 10500, 17, 210, 17, 39.59, 0, 2, 1, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70c26ef-3497-11ec-9103-34e6d760b36f', 'P053', 'Tây Ninh', 9235, 294, 1400, 150, 10500, 146, 210, 18, 119.29, 20.79, 2, 1, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70c2992-3497-11ec-9103-34e6d760b36f', 'P054', 'Thái Bình', 132, 1185, 1400, 150, 10500, 0, 210, 19, 35.65, 0, 9, 1, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70c2c34-3497-11ec-9103-34e6d760b36f', 'P055', 'Thái Nguyên', 23, 373, 1400, 150, 10500, 0, 210, 21, 36.33, 0, 6, 1, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70c2f59-3497-11ec-9103-34e6d760b36f', 'P056', 'Thanh Hóa', 654, 332, 1700, 170, 13500, 5, 200, 25, 36.33, 0, 5, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70c31dc-3497-11ec-9103-34e6d760b36f', 'P057', 'Thừa Thiên Huế', 889, 225, 1700, 170, 13500, 11, 200, 21, 52.06, 0, 4, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70c3426-3497-11ec-9103-34e6d760b36f', 'P058', 'Tiền Giang', 14612, 710, 1750, 175, 14600, 376, 190, 26, 52.06, 0, 5, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70c365b-3497-11ec-9103-34e6d760b36f', 'P059', 'Trà Vinh', 1836, 428, 1750, 175, 11600, 20, 240, 20, 46.88, 0, 1, 1, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70c3922-3497-11ec-9103-34e6d760b36f', 'P060', 'Tuyên Quang', 11, 135, 1550, 155, 9600, 0, 90, 18, 41.48, 0, 4, 1, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70c3ce8-3497-11ec-9103-34e6d760b36f', 'P061', 'Vĩnh Long', 2396, 693, 2950, 310, 19800, 45, 90, 18, 70.99, 0, 4, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70c4546-3497-11ec-9103-34e6d760b36f', 'P062', 'Vĩnh Phúc', 267, 934, 1950, 185, 11800, 3, 190, 20, 64.94, 0, 5, 2, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('b70c48e1-3497-11ec-9103-34e6d760b36f', 'P063', 'Yên Bái', 13, 112, 1950, 185, 11800, 0, 210, 19, 102.25, 7.72, 5, 1, 'Group2', '2021-10-24 00:00:00', NULL, NULL);


INSERT INTO `dss.v1`.testkit(TestKitId, TestKitCode, TestKitName, Amount, CreatedBy, CreatedDate, ModifiedBy, ModifiedDate) VALUES
('f491a494-3486-11ec-9103-34e6d760b36f', 'TK001', 'Flowflex SARSCoV-2 Antigen Rapid Test', 500000, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('f49f5a49-3486-11ec-9103-34e6d760b36f', 'TK002', 'Biosynex Covid-19 Ag BSS', 500000, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('f49f610b-3486-11ec-9103-34e6d760b36f', 'TK003', 'V Trust Covid-19 Antigen Rapid Test', 500000, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('f49f63cf-3486-11ec-9103-34e6d760b36f', 'TK004', 'COVID-19 Ag', 800000, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('f49f6603-3486-11ec-9103-34e6d760b36f', 'TK005', 'BioCredit COVID -19 Ag', 800000, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('f49f8918-3486-11ec-9103-34e6d760b36f', 'TK006', 'CareStart COVID-19 Antigen', 800000, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('f49f8ce9-3486-11ec-9103-34e6d760b36f', 'TK007', 'GenBody COVID-19 Ag', 800000, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('f49f8f11-3486-11ec-9103-34e6d760b36f', 'TK008', 'Asan Easy Test COVID-19 Ag', 800000, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('f49f9133-3486-11ec-9103-34e6d760b36f', 'TK009', 'SARS-CoV-2 Rapid Antigen Test', 1000000, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('f49f933e-3486-11ec-9103-34e6d760b36f', 'TK010', 'Panbio COVID-19 Ag Rapid Test Device', 1000000, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('f49f9543-3486-11ec-9103-34e6d760b36f', 'TK011', 'Espline SARS-CoV-2', 1000000, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('f49f975f-3486-11ec-9103-34e6d760b36f', 'TK012', 'Standard Q COVID-19 Ag Test', 1000000, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('f49f996b-3486-11ec-9103-34e6d760b36f', 'TK013', 'Humasis COVID-19 Ag Test', 1000000, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('f49f9b89-3486-11ec-9103-34e6d760b36f', 'TK014', 'SGTi-flex COVID-19 Ag', 1000000, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('f49f9d71-3486-11ec-9103-34e6d760b36f', 'TK015', 'Panbio COVID -19 Ag Rapid', 1000000, 'Group2', '2021-10-24 00:00:00', NULL, NULL);


INSERT INTO `dss.v1`.vaccine(VaccineId, VaccineCode, VaccineName, Amount, CreatedBy, CreatedDate, ModifiedBy, ModifiedDate) VALUES
('f9aad1b7-3484-11ec-9103-34e6d760b36f', 'V001', 'AstraZeneca', 1000000, 'Group2', '2021-10-24 00:00:00', NULL, '2021-12-26 17:10:30'),
('f9d094bf-3484-11ec-9103-34e6d760b36f', 'V002', 'Pfizer', 1500000, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('f9d223ca-3484-11ec-9103-34e6d760b36f', 'V003', 'Sinopharm', 500000, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('f9d22871-3484-11ec-9103-34e6d760b36f', 'V004', 'Moderna', 800000, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('f9d229fd-3484-11ec-9103-34e6d760b36f', 'V005', 'Sputnik V', 4000000, 'Group2', '2021-10-24 00:00:00', NULL, NULL),
('f9d22b13-3484-11ec-9103-34e6d760b36f', 'V006', 'Vero Cell', 2000000, 'Group2', '2021-10-24 00:00:00', NULL, NULL);

CREATE DEFINER = 'root'@'localhost'
PROCEDURE `dss.v1`.Proc_Update_BreathMachine(IN  BreathMachineId char(36), IN BreathMachineCode VARCHAR(20), IN BreathMachineName VARCHAR(255), IN Amount INT, IN CreatedBy VARCHAR(20), IN CreatedDate DATE, IN ModifiedBy VARCHAR(20), IN ModifiedDate date)
BEGIN

  UPDATE BreathMachine b
  SET
    b.BreathMachineCode = BreathMachineCode -- BreathMachineCode - VARCHAR(20) NOT NULL
   ,b.BreathMachineName = BreathMachineName -- BreathMachinceName - VARCHAR(255) NOT NULL
   ,b.Amount = Amount -- Amount - INT
   ,b.ModifiedBy = ModifiedBy -- ModifiedBy - VARCHAR(20)
   ,b.ModifiedDate = NOW() -- ModifiedDate - DATE
  WHERE
    b.BreathMachineId = BreathMachineId -- BreathMachinceId - CHAR(36) NOT NULL
  ;
  
END;

CREATE DEFINER = 'root'@'localhost'
PROCEDURE `dss.v1`.Proc_Update_HospitalBed(IN HospitalBedId CHAR(36), IN HospitalBedCode VARCHAR(20), IN Amount INT, IN CreatedDate DATETIME, IN CreatedBy VARCHAR(20), IN ModifiedDate DATETIME, IN ModifiedBy VARCHAR(20))
BEGIN

  UPDATE HospitalBed h
  SET
    h.HospitalBedCode = HospitalBedCode -- HospitalBedCode - VARCHAR(20) NOT NULL
   ,h.Amount = Amount -- Amount - INT
   ,h.ModifiedDate = NOW() -- ModifiedDate - DATETIME
   ,h.ModifiedBy = ModifiedBy -- ModifiedBy - VARCHAR(20)
  WHERE
    h.HospitalBedId = HospitalBedId -- HospitalBedId - CHAR(36) NOT NULL
  ;

END;

CREATE DEFINER = 'root'@'localhost'
PROCEDURE `dss.v1`.Proc_Update_Province(IN ProvinceId CHAR(36), IN ProvinceCode VARCHAR(20), IN ProvinceName VARCHAR(255), IN NumberCase INT, IN PopulationDensity INT, IN HospitalBed INT, IN BreathMachine INT, IN TestKit INT, IN NumberDeath INT, IN NumberDoctorDispatch INT, IN NumberHospital INT, IN OneShotInjectionRate DOUBLE, IN TwoShotInjectionRate DOUBLE, IN IndustrialArea INT, IN EpidemicLevel INT, IN CreatedBy VARCHAR(20), IN CreatedDate DATETIME, IN ModifiedBy VARCHAR(20), IN ModifiedDate datetime)
BEGIN
  
  UPDATE Province p
  SET
    p.ProvinceCode = ProvinceCode
   ,p.ProvinceName = ProvinceName -- ProvinceName - VARCHAR(255) NOT NULL
   ,p.NumberCase = NumberCase -- NumberCase - INT
   ,p.PopulationDensity = PopulationDensity -- PopulationDensity - INT
   ,p.HospitalBed = HospitalBed -- HospitalBed - INT
   ,p.BreathMachine = BreathMachine -- BreathMachine - INT
   ,p.TestKit = TestKit -- TestKit - INT
   ,p.NumberDeath = NumberDeath -- NumberDeath - INT
   ,p.NumberDoctorDispatch = NumberDoctorDispatch -- NumberDoctorDispatch - INT
   ,p.NumberHospital = NumberHospital -- NumberHospital - INT
   ,p.OneShotInjectionRate = OneShotInjectionRate -- OneShotInjectionRate - DOUBLE
   ,p.TwoShotInjectionRate = TwoShotInjectionRate -- TwoShotInjectionRate - DOUBLE
   ,p.IndustrialArea = IndustrialArea -- IndustrialArea - INT
   ,p.EpidemicLevel = EpidemicLevel -- EpidemicLevel - INT
   ,p.ModifiedBy = ModifiedBy -- ModifiedBy - VARCHAR(20)
   ,p.ModifiedDate = NOW() -- ModifiedDate - DATETIME
  WHERE
    p.ProvinceId = ProvinceId -- ProvinceId - CHAR(36) NOT NULL
  ;

END;

CREATE DEFINER = 'root'@'localhost'
PROCEDURE `dss.v1`.Proc_Update_TestKit(IN TestKitId CHAR(36), IN TestKitCode VARCHAR(20), IN TestKitName VARCHAR(255), IN Amount INT, IN CreatedDate DATETIME, IN CreatedBy VARCHAR(20), IN ModifiedDate DATETIME, IN ModifiedBy VARCHAR(20))
BEGIN
  UPDATE testkit t
  SET
    t.TestKitCode = TestKitCode -- TestKitCode - VARCHAR(20) NOT NULL
   ,t.TestKitName = TestKitName -- TestKitName - VARCHAR(255) NOT NULL
   ,t.Amount = Amount -- Amount - INT
   ,t.ModifiedBy = ModifiedBy -- ModifiedBy - VARCHAR(20)
   ,t.ModifiedDate = NOW() -- ModifiedDate - DATETIME
  WHERE
    t.TestKitId = TestKitId -- TestKitId - CHAR(36) NOT NULL
  ;
END;

CREATE DEFINER = 'root'@'localhost'
PROCEDURE `dss.v1`.Proc_Update_Vaccine(IN VaccineId CHAR(36), IN VaccineCode VARCHAR(20), IN VaccineName VARCHAR(255), IN Amount INT, IN CreatedBy VARCHAR(20), IN CreatedDate DATETIME, IN ModifiedBy VARCHAR(20), IN ModifiedDate datetime)
BEGIN
  UPDATE vaccine v
  SET
   v.VaccineCode = VaccineCode, -- VaccineCode - VARCHAR(20) NOT NULL
   v.VaccineName = VaccineName, -- VaccineName - VARCHAR(255) NOT NULL
   v.Amount = Amount, -- Amount - INT
   v.ModifiedBy = ModifiedBy, -- ModifiedBy - VARCHAR(20)
   v.ModifiedDate = NOW() -- ModifiedDate - DATETIME
  WHERE
    v.VaccineId = VaccineId -- VaccineId - CHAR(36) NOT NULL
  ;
END;